package com.finfotechp2p.processdump;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class flowList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String userType;
	private java.lang.Integer pmid;
	private java.lang.String client;
	private java.lang.String processList;

	public flowList() {
	}

	public java.lang.String getUserType() {
		return this.userType;
	}

	public void setUserType(java.lang.String userType) {
		this.userType = userType;
	}

	public java.lang.Integer getPmid() {
		return this.pmid;
	}

	public void setPmid(java.lang.Integer pmid) {
		this.pmid = pmid;
	}

	public java.lang.String getClient() {
		return this.client;
	}

	public void setClient(java.lang.String client) {
		this.client = client;
	}

	public java.lang.String getProcessList() {
		return this.processList;
	}

	public void setProcessList(java.lang.String processList) {
		this.processList = processList;
	}

	public flowList(java.lang.String userType, java.lang.Integer pmid,
			java.lang.String client, java.lang.String processList) {
		this.userType = userType;
		this.pmid = pmid;
		this.client = client;
		this.processList = processList;
	}

}